import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { generate } from './pipeline.js';

const root=path.dirname(fileURLToPath(import.meta.url)),dataDir=path.join(root,'data');
async function loadEnv(){try{let raw=await fs.readFile(path.join(root,'.env'),'utf8');for(let line of raw.split(/\r?\n/)){let m=line.match(/^([A-Z_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}catch{}}
await loadEnv();if(!process.env.ADMIN_PASSWORD||process.env.ADMIN_PASSWORD.length<6||!process.env.APP_SECRET||process.env.APP_SECRET.length<32){console.error('ADMIN_PASSWORD (6자 이상)와 APP_SECRET (32자 이상)을 .env에 설정하세요.');process.exit(1)}
await fs.mkdir(dataDir,{recursive:true});const secret=crypto.createHash('sha256').update(process.env.APP_SECRET).digest(),settingsFile=path.join(dataDir,'settings.enc'),jobs=new Map(),attempts=new Map();let running=false;
function encrypt(obj){let iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',secret,iv),body=Buffer.concat([cipher.update(JSON.stringify(obj)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64')}
function decrypt(raw){let b=Buffer.from(raw,'base64'),d=crypto.createDecipheriv('aes-256-gcm',secret,b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]).toString())}
async function storedKeys(){try{return decrypt(await fs.readFile(settingsFile,'utf8'))}catch(e){if(e.code==='ENOENT')return {};throw Error('키 설정을 읽지 못했습니다. APP_SECRET이 변경되었는지 확인하세요.')}}
async function keys(){let s=await storedKeys();return {openai:s.openai||process.env.OPENAI_API_KEY||undefined,pexels:s.pexels||process.env.PEXELS_API_KEY||undefined,gemini:s.gemini||process.env.GEMINI_API_KEY||undefined,elevenlabs:s.elevenlabs||process.env.ELEVENLABS_API_KEY||undefined}}
async function saveKeys(v){let tmp=settingsFile+'.tmp';await fs.writeFile(tmp,encrypt(v),{mode:0o600});await fs.rename(tmp,settingsFile)}
const cookieName='lvm_session';function sign(v){return crypto.createHmac('sha256',secret).update(v).digest('hex')}
function authorized(req){let match=(req.headers.cookie||'').match(/(?:^|;\s*)lvm_session=([^;]+)/);if(!match)return false;let [exp,sig]=decodeURIComponent(match[1]).split('.');if(!exp||!sig||Number(exp)<Date.now())return false;return crypto.timingSafeEqual(Buffer.from(sign(exp)),Buffer.from(sig))}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj))}
async function body(req){let chunks=[],size=0;for await(let chunk of req){size+=chunk.length;if(size>50000)throw Error('요청 크기가 너무 큽니다.');chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString()||'{}')}
function sameOrigin(req){let origin=req.headers.origin;if(!origin)return true;let host=req.headers.host;return new URL(origin).host===host&&['http:','https:'].includes(new URL(origin).protocol)}
function validUrl(u){try{let x=new URL(u);return ['http:','https:'].includes(x.protocol)&&x.hostname.includes('.')&&!x.username&&!x.password}catch{return false}}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
let server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'");if(req.method==='POST'&&!sameOrigin(req))return json(res,403,{error:'요청 출처가 다릅니다.'});if(u.pathname==='/api/login'&&req.method==='POST'){let ip=req.socket.remoteAddress||'unknown',record=attempts.get(ip)||{n:0,until:0};if(record.n>=8&&record.until>Date.now())return json(res,429,{error:'잠시 후 다시 시도하세요.'});let b=await body(req),a=Buffer.from(String(b.password||'')),expected=Buffer.from(process.env.ADMIN_PASSWORD),ok=a.length===expected.length&&crypto.timingSafeEqual(a,expected);if(!ok){attempts.set(ip,{n:record.n+1,until:Date.now()+60000});return json(res,401,{error:'비밀번호를 확인하세요.'})}attempts.delete(ip);let exp=String(Date.now()+12*3600e3);res.setHeader('Set-Cookie',`${cookieName}=${exp}.${sign(exp)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${req.socket.encrypted?' ; Secure':''}`);return json(res,200,{ok:true})}
if(u.pathname==='/api/logout'&&req.method==='POST'){res.setHeader('Set-Cookie',`${cookieName}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${req.socket.encrypted?' ; Secure':''}`);return json(res,200,{ok:true})}if(u.pathname.startsWith('/api/')&&!authorized(req))return json(res,401,{error:'로그인이 필요합니다.'});if(u.pathname==='/api/session')return json(res,200,{ok:true});if(u.pathname==='/api/settings/reveal'&&req.method==='GET'){let k=await keys();return json(res,200,{openai:k.openai||'',pexels:k.pexels||'',gemini:k.gemini||'',elevenlabs:k.elevenlabs||''})}if(u.pathname==='/api/settings'&&req.method==='GET'){let k=await keys();return json(res,200,{configured:{openai:!!k.openai,pexels:!!k.pexels,gemini:!!k.gemini,elevenlabs:!!k.elevenlabs}})}if(u.pathname==='/api/settings'&&req.method==='POST'){let b=await body(req),k=await storedKeys();for(let name of ['openai','pexels','gemini','elevenlabs'])if(Object.hasOwn(b,name)){if(typeof b[name]!=='string'||b[name].length>500)throw Error('키 형식이 올바르지 않습니다.');if(b[name].trim())k[name]=b[name].trim();else if(b.clear===name)delete k[name]}await saveKeys(k);return json(res,200,{configured:{openai:!!k.openai,pexels:!!k.pexels,gemini:!!k.gemini,elevenlabs:!!k.elevenlabs}})}
if(u.pathname==='/api/generate'&&req.method==='POST'){if(running)return json(res,429,{error:'현재 영상 생성 작업이 진행 중입니다.'});let k=await keys();if(!k.openai)return json(res,400,{error:'설정에서 OpenAI 키를 저장하세요.'});let b=await body(req),urls=Array.isArray(b.urls)?b.urls.slice(0,8):[],o=b.options||{};if(!urls.length&&!String(b.manual||'').trim())throw Error('링크 또는 직접 입력한 내용을 넣어 주세요.');if(urls.some(x=>!validUrl(x)))throw Error('올바른 공개 웹페이지 링크만 입력하세요.');let format=['short','long'].includes(o.format)?o.format:'short',allowed=format==='short'?[15,30,45,60]:[120,180,300,480],options={format,style:['stock','photo','anime'].includes(o.style)?o.style:(o.style==='real'?'stock':'stock'),duration:allowed.includes(Number(o.duration))?Number(o.duration):(format==='short'?30:180),purpose:String(o.purpose||'정보 설명').slice(0,40),aiClips:Math.min(4,Math.max(0,Number(o.aiClips)||0)),subtitles:o.subtitles!==false,voice:['coral','nova','shimmer','sage','alloy','echo','onyx','fable','ash','ballad','verse'].includes(o.voice)?o.voice:'coral'};if(options.aiClips&&!k.gemini)return json(res,400,{error:'AI 영상 장면을 사용하려면 Gemini 키를 저장하거나 장면 수를 0으로 바꾸세요.'});let id=crypto.randomUUID(),job={id,status:'queued',phase:'대기',detail:'',options,urls,manual:String(b.manual||'').slice(0,20000),dir:path.join(dataDir,'jobs',id)};jobs.set(id,job);running=true;setImmediate(async()=>{try{job.status='running';let result=await generate(job,k,(phase,detail)=>{job.phase=phase;job.detail=detail});Object.assign(job,{status:'done',result})}catch(e){job.status='failed';job.error=e.message;console.error('Job',id,e)}finally{running=false}});return json(res,202,{id})}
let match=u.pathname.match(/^\/api\/jobs\/([a-f0-9-]+)(\/download|\/storyboard|\/captions|\/facts|\/preview)?$/);if(match){let j=jobs.get(match[1]);if(!j)return json(res,404,{error:'작업을 찾지 못했습니다. 서버를 재시작하면 진행 상태가 초기화됩니다.'});if(match[2]==='/preview'){if(j.status!=='done')return json(res,409,{error:'작업이 아직 끝나지 않았습니다.'});let bytes=await fs.readFile(path.join(j.dir,'final.mp4'));res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':bytes.length,'Cache-Control':'no-store'});return res.end(bytes)}if(match[2]){if(j.status!=='done')return json(res,409,{error:'작업이 아직 끝나지 않았습니다.'});let map={'/download':['final.mp4','video/mp4','',''],'/storyboard':['storyboard.json','application/json; charset=utf-8','-대본','.json'],'/captions':['captions.srt','text/plain; charset=utf-8','-자막','.srt'],'/facts':['facts.txt','text/plain; charset=utf-8','-팩트','.txt']},[fname,ctype,suffix,ext]=map[match[2]],base=(((j.result&&j.result.title)||'onvideo').replace(/[\/\\?%*:|"<>\r\n]+/g,' ').trim().slice(0,50)||'onvideo'),dl=match[2]==='/download'?base+'.mp4':base+suffix+ext,bytes=await fs.readFile(path.join(j.dir,fname));res.writeHead(200,{'Content-Type':ctype,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(dl)}`,'Content-Length':bytes.length,'Cache-Control':'no-store'});return res.end(bytes)}return json(res,200,{id:j.id,status:j.status,phase:j.phase,detail:j.detail,error:j.error,result:j.result&&{title:j.result.title,seconds:j.result.seconds,scenes:j.result.scenes,credits:j.result.credits}})}
if(req.method!=='GET')return json(res,405,{error:'지원하지 않는 요청입니다.'});let relative=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!/^[a-zA-Z0-9._/-]+$/.test(relative)||relative.includes('..'))return json(res,404,{error:'찾을 수 없습니다.'});let file=path.join(root,'public',relative),content=await fs.readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(content)}catch(e){if(e.code==='ENOENT')return json(res,404,{error:'찾을 수 없습니다.'});console.error(e);json(res,400,{error:e.message||'요청을 처리하지 못했습니다.'})}});
let port=Number(process.env.PORT)||3000;server.listen(port,'0.0.0.0',()=>console.log('Link Video Maker running on port',port));
